[2024-10-03T09:13:15.800+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: smiles_to_s3.extract_data manual__2024-10-03T09:13:12.411063+00:00 [queued]>
[2024-10-03T09:13:15.805+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: smiles_to_s3.extract_data manual__2024-10-03T09:13:12.411063+00:00 [queued]>
[2024-10-03T09:13:15.805+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-03T09:13:15.813+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract_data> on 2024-10-03 09:13:12.411063+00:00
[2024-10-03T09:13:15.828+0000] {standard_task_runner.py:57} INFO - Started process 14323 to run task
[2024-10-03T09:13:15.837+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'smiles_to_s3', 'extract_data', 'manual__2024-10-03T09:13:12.411063+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphnbmqedq']
[2024-10-03T09:13:15.851+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask extract_data
[2024-10-03T09:13:15.891+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-03T09:13:15.956+0000] {task_command.py:410} INFO - Running <TaskInstance: smiles_to_s3.extract_data manual__2024-10-03T09:13:12.411063+00:00 [running]> on host 7039014ebb04
[2024-10-03T09:13:16.029+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='smiles_to_s3' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T09:13:12.411063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T09:13:12.411063+00:00'
[2024-10-03T09:13:16.030+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 42, in extract_smiles_data
    data = pd.read_sql(query, engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 608, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2054, in execute
    cur = self.con.cursor()
AttributeError: 'function' object has no attribute 'cursor'
[2024-10-03T09:13:16.039+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=smiles_to_s3, task_id=extract_data, execution_date=20241003T091312, start_date=20241003T091315, end_date=20241003T091316
[2024-10-03T09:13:16.049+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 31 for task extract_data ('function' object has no attribute 'cursor'; 14323)
[2024-10-03T09:13:16.062+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-10-03T09:13:16.079+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
