[2024-10-01T13:51:46.725+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: smiles_to_s3.save_to_s3 manual__2024-10-01T13:51:42.262664+00:00 [queued]>
[2024-10-01T13:51:46.730+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: smiles_to_s3.save_to_s3 manual__2024-10-01T13:51:42.262664+00:00 [queued]>
[2024-10-01T13:51:46.730+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-01T13:51:46.737+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): save_to_s3> on 2024-10-01 13:51:42.262664+00:00
[2024-10-01T13:51:46.740+0000] {standard_task_runner.py:57} INFO - Started process 207 to run task
[2024-10-01T13:51:46.742+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'smiles_to_s3', 'save_to_s3', 'manual__2024-10-01T13:51:42.262664+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpre6d5coo']
[2024-10-01T13:51:46.743+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask save_to_s3
[2024-10-01T13:51:46.752+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-01T13:51:46.774+0000] {task_command.py:410} INFO - Running <TaskInstance: smiles_to_s3.save_to_s3 manual__2024-10-01T13:51:42.262664+00:00 [running]> on host e9d37ae1a381
[2024-10-01T13:51:46.837+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='smiles_to_s3' AIRFLOW_CTX_TASK_ID='save_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T13:51:42.262664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T13:51:42.262664+00:00'
[2024-10-01T13:51:47.153+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 81, in save_to_s3
    df.to_excel(output, index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2024-10-01T13:51:47.166+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=smiles_to_s3, task_id=save_to_s3, execution_date=20241001T135142, start_date=20241001T135146, end_date=20241001T135147
[2024-10-01T13:51:47.173+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task save_to_s3 (No module named 'openpyxl'; 207)
[2024-10-01T13:51:47.180+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-10-01T13:51:47.195+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
